### PR TITLE
Bug 1905119: support custom CA bundle for AWS API

### PR DESCRIPTION
**Pull request by staebler**
The determination about whether a custom CA bundle is being used is assessed when the operator starts. This can lead to incorrect behavior if the kube-cloud-config ConfigMap has not yet been created in the openshit-config-managed namespace when the operator starts. Instead of only looking for the ConfigMap at start-up, these changes will have the operator looking for the ConfigMap on every reconcile and adjusting the yaml for the controller asset accordingly.

### CODE REVIEW

**Comment by staebler** [comment]
This is my attempt at using replacement strings for the deployment asset that will look for the kube-cloud-config ConfigMap as the operator runs rather than just at initialization.

**Comment by staebler** [comment]
This PR needs https://github.com/openshift/library-go/pull/965 to merge first as it is currently using a fork of library-go with those changes.

/hold

**Review by bertinatto — COMMENTED** [review]
Thanks for following up with this @staebler! I think this patch addresses the concerns we had related to the operator startup and templating.

Let's wait for the library-go patch to get in so we can continue here.

Edit: There seems to be some panic going on:

```
pods/openshift-cluster-csi-drivers_aws-ebs-csi-driver-operator-6b86c8c97-dzltt_aws-ebs-csi-driver-operator.log.gz:E1207 15:34:43.495828       1 runtime.go:78] Observed a panic: &errors.errorString{s:"v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Volumes: []v1.Volume: v1.Volume.VolumeSource: ConfigMap: v1.ConfigMapVolumeSource.Optional: ReadBool: expect t or f, but found \", error found in #10 byte of ...|ptional\":\"${true}\"},|..., bigger context ...|onfigMap\":{\"name\":\"kube-cloud-config\",\"optional\":\"${true}\"},\"name\":\"ca-bundle\"},{\"emptyDir\":{},\"name|..."} (v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Volumes: []v1.Volume: v1.Volume.VolumeSource: ConfigMap: v1.ConfigMapVolumeSource.Optional: ReadBool: expect t or f, but found ", error found in #10 byte of ...|ptional":"${true}"},|..., bigger context ...|onfigMap":{"name":"kube-cloud-config","optional":"${true}"},"name":"ca-bundle"},{"emptyDir":{},"name|...)```

**Comment by bertinatto** [comment]
@staebler do you think you could use the hooks that was added recently to library-go?

Example: https://github.com/openshift/aws-ebs-csi-driver-operator/pull/104/commits/5f697e65c519099fa22bb03e923cde5d78c9401c

**Comment by staebler** [comment]
> @staebler do you think you could use the hooks that was added recently to library-go?
> 
> Example: [5f697e6](https://github.com/openshift/aws-ebs-csi-driver-operator/commit/5f697e65c519099fa22bb03e923cde5d78c9401c)

/close in favor of https://github.com/openshift/aws-ebs-csi-driver-operator/pull/111

**Pull request closed without merging**
