### PR TITLE
STOR-764: Change the default StorageClass to the CSI one (AWS)

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-764

- bump(openshift/api): to get CSI migration gates switched off
- bump k8s 1.25 libs to resolve build failures
- [STOR-764](https://issues.redhat.com//browse/STOR-764): Change the default StorageClass to the CSI one

/cc @openshift/storage

### CODE REVIEW

**Comment by ropatil010** [comment]
Tried premerge verification: 
rohitpatil@ropatil-mac Downloads % oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.ci.test-2022-09-01-084106-ci-ln-jpdimx2-latest   True        False         8m59s   Cluster version is 4.12.0-0.ci.test-2022-09-01-084106-ci-ln-jpdimx2-latest

rohitpatil@ropatil-mac Downloads % oc get sc
NAME      PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   25m
gp3-csi   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   25m

Note: There is no default mentioned among the present 2 sc(gp2-csi, gp3-csi). 

Additional info: 
In azure platform after CSI migration, 1 csi(managed-csi) mentioned with default one
rohitpatil@ropatil-mac Downloads % oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   161m
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   161m

Is this expected in AWS?  
cc: @dobsonj @duanwei33

**Comment by ropatil010** [comment]
Platform: AWS
Showing atleast 1default sc after removing intree provisioner 
clusterversion: 4.12.0-0.ci.test-2022-09-02-062332-ci-ln-c8ivfm2-lates
Test for provisioning of volume with types of sc, Showing results below 

rohitpatil@ropatil-mac Downloads % oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   42m
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   42m

rohitpatil@ropatil-mac Downloads % oc get pvc,pod -n testropatil -o wide
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   VOLUMEMODE
persistentvolumeclaim/mypvc-csi   Bound    pvc-2ca927a4-d921-49ea-985c-7b2d38f9d8e2   1Gi        RWO            gp3-csi        96s   Filesystem
NAME                         READY   STATUS    RESTARTS   AGE   IP            NODE                           NOMINATED NODE   READINESS GATES
pod/mydep-776f4cb754-4574w   1/1     Running   0          90s   10.129.2.19   ip-10-0-173-184.ec2.internal   <none>           <none>

rohitpatil@ropatil-mac Downloads % oc get pvc,pod -n testropatil -o wide
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   VOLUMEMODE
persistentvolumeclaim/mypvc-csi   Bound    pvc-f3f13dbe-f815-464b-a96b-42a0c4d103a0   1Gi        RWO            gp2-csi        19s   Filesystem
NAME                         READY   STATUS    RESTARTS   AGE   IP            NODE                           NOMINATED NODE   READINESS GATES
pod/mydep-776f4cb754-4rgh7   1/1     Running   0          14s   10.129.2.20   ip-10-0-173-184.ec2.internal   <none>           <none>

Working as expected.

**Comment by ropatil010** [comment]
Tested Upgrade scenario and sharing result. Working as expected. 

AWS 
rohitpatil@ropatil-mac Downloads % oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.11.0-0.nightly-2022-09-02-184920   True        False         28m     Cluster version is 4.11.0-0.nightly-2022-09-02-184920

rohitpatil@ropatil-mac Downloads % oc get sc
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   true                   43m
gp2-csi         ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   42m
gp3-csi         ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   42m

rohitpatil@ropatil-mac Downloads % oc get co storage
'NAME      VERSION                              AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
storage   4.11.0-0.nightly-2022-09-02-184920   True        False         False      59m  

rohitpatil@ropatil-mac Downloads % oc get pvc,pod -n testropatil  -o wide
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   VOLUMEMODE
persistentvolumeclaim/mypvc-csi   Bound    pvc-b14b85d4-9c37-499e-8b6c-478494ea8705   1Gi        RWO            gp2            38s   Filesystem
NAME                         READY   STATUS    RESTARTS   AGE   IP            NODE                                        NOMINATED NODE   READINESS GATES
pod/mydep-776f4cb754-jqwg2   1/1     Running   0          25s   10.128.2.17   ip-10-0-195-11.us-east-2.compute.internal   <none>           <none>

rohitpatil@ropatil-mac Downloads % oc get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                   STORAGECLASS   REASON   AGE
pvc-b14b85d4-9c37-499e-8b6c-478494ea8705   1Gi        RWO            Delete           Bound    testropatil/mypvc-csi   gp2                     25s

rohitpatil@ropatil-mac Downloads % oc exec pod/mydep-776f4cb754-jqwg2 -n testropatil /bin/bash -i -- sh -c "echo 'helloworld' > /mnt/storage/testfile1.txt"
rohitpatil@ropatil-mac Downloads % oc exec pod/mydep-776f4cb754-jqwg2 -n testropatil /bin/bash -i -- sh -c "cat /mnt/storage/testfile1.txt"
helloworld

Upgrade cluster 

rohitpatil@ropatil-mac Downloads % oc get clusterversion  
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.ci.test-2022-09-05-021557-ci-ln-q95c9r2-latest   True        False         4m22s   Cluster version is 4.12.0-0.ci.test-2022-09-05-021557-ci-ln-q95c9r2-latest

rohitpatil@ropatil-mac Downloads % oc get sc
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   true                   153m
gp2-csi         ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   153m
gp3-csi         ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   153m

rohitpatil@ropatil-mac Downloads % oc get pvc,pod -n testropatil -o wide
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE    VOLUMEMODE
persistentvolumeclaim/mypvc-csi    Bound    pvc-b14b85d4-9c37-499e-8b6c-478494ea8705   1Gi        RWO            gp2            113m   Filesystem
persistentvolumeclaim/mypvc-csi2   Bound    pvc-067b73b6-30ec-46bc-b6ef-7968b4eb9a72   1Gi        RWO            gp2            25s    Filesystem
NAME                          READY   STATUS    RESTARTS   AGE   IP           NODE                                        NOMINATED NODE   READINESS GATES
pod/mydep-776f4cb754-lkknq    1/1     Running   0          21m   10.128.2.6   ip-10-0-195-11.us-east-2.compute.internal   <none>           <none>
pod/mydep2-75976675d4-fl569   1/1     Running   0          20s   10.128.2.8   ip-10-0-195-11.us-east-2.compute.internal   <none>           <none>

rohitpatil@ropatil-mac Downloads % oc get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS   REASON   AGE
pvc-067b73b6-30ec-46bc-b6ef-7968b4eb9a72   1Gi        RWO            Delete           Bound    testropatil/mypvc-csi2   gp2                     40s
pvc-b14b85d4-9c37-499e-8b6c-478494ea8705   1Gi        RWO            Delete           Bound    testropatil/mypvc-csi    gp2                     113m

rohitpatil@ropatil-mac Downloads % oc exec pod/mydep-776f4cb754-lkknq -n testropatil /bin/bash -i -- sh -c "echo 'hellowordl2' > /mnt/storage/testfile2.txt"
rohitpatil@ropatil-mac Downloads % oc exec pod/mydep-776f4cb754-lkknq -n testropatil /bin/bash -i -- sh -c "cat /mnt/storage/testfile2.txt"
hellowordl2

rohitpatil@ropatil-mac Downloads % oc exec pod/mydep2-75976675d4-fl569 -n testropatil /bin/bash -i -- sh -c "echo 'hellowordl3' > /mnt/storage/testfile3.txt"
rohitpatil@ropatil-mac Downloads % oc exec pod/mydep2-75976675d4-fl569 -n testropatil /bin/bash -i -- sh -c "cat /mnt/storage/testfile3.txt"
hellowordl3


/label qe-approved

**Comment by dobsonj** [comment]
/assign @lpettyjo 
for docs-approved
/assign @mhackett
for px-approved

**Pull request merged**
