### PR TITLE
Bug 1898045: redeploy CSI Controller Deployment when secret changes 

### PR DESCRIPTION
**Pull request by bertinatto**
This PR uses changes from openshift/library-go#976 to redeploy the Controller Deployment when the secret changes.

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
 openshift/library-go#976  needs to be merged first.

**Comment by bertinatto** [comment]
/hold cancel
openshift/library-go#976 has been merged.
@openshift/storage PTAL

**Comment by gnufied** [comment]
Having reviewed the library-go changes, these changes look good to me.

/lgtm

**Pull request merged**
