### PR TITLE
Bug 1866339: Update to go 1.14 and OCP 4.6

### PR DESCRIPTION
**Pull request by bertinatto**
/assign @jsafrane

### CODE REVIEW

**Comment by jsafrane** [comment]
```
k8s.io/klog@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

```

`go mod vendor` missing? Btw, moving to klog/v2 would be helpful, either here or in a separate PR.

**Comment by bertinatto** [comment]
> ```
> k8s.io/klog@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
> ```
> 
> `go mod vendor` missing? Btw, moving to klog/v2 would be helpful, either here or in a separate PR.

Updated to klog/v2. Now I see this:

```
 > diff --no-dereference -N -r current/vendor/modules.txt updated/vendor/modules.txt
> 34d33
> < ## explicit
> 100d98
> < ## explicit
> 150d147
> < ## explicit
> 160d156
> < ## explicit
> 190d185
> < ## explicit
> 211d205
> < ## explicit
> 214d207
> < ## explicit
> 426d418
> < ## explicit
> 601d592
> < ## explicit
> 773d763
> < ## explicit
> 783d772
> < ## explicit
ERROR: Content of 'vendor/' directory doesn't match 'go.mod' configuration and the overrides in 'deps.diff'!
Did you run `go mod vendor`?
If this is an intentional change (a carry patch) please update the 'deps.diff' using 'make update-deps-overrides'. 
```

I think whatever is running `go mod vendor` in `prow/verify` job has go 1.13, because it produces different results than go 1.14.

On the other hand, `prow/images` uses go 1.14, so if I run `go mod vendor` with go 1.13 (in my dev box), that job will always fail.

To summarize, I think we can't migrate to go 1.14 while  `prow/verify` job uses go 1.13.

**Comment by jsafrane** [comment]
moving further:
```
k8s.io/klog/v2@v2.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
``` 
Not sure what's wron g there...

**Comment by bertinatto** [comment]
Depends on https://github.com/openshift/release/pull/10590 to fix the verify job.

**Pull request merged**
