### PR TITLE
TODO list has been migrated to GH issues

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

### CODE REVIEW

**Comment by huffmanca** [comment]
Do we have issues for the following items?

> - [ ] Sync status when error happens while syncing resources other than Deployment and DaemonSet?
> - [ ] 20 min for resyncing is OK in OLM-managed operators? Check other operators

**Comment by bertinatto** [comment]
> Do we have issues for the following items?
> 
> > * [ ]  Sync status when error happens while syncing resources other than Deployment and DaemonSet?
> > * [ ]  20 min for resyncing is OK in OLM-managed operators? Check other operators

I didn't create issues for those because I thought they were not necessary. Let me know if you disagree.

**Comment by huffmanca** [comment]
Seems fine to me! I know the rest either aren't relevant, or have existing cards elsewhere (such as JIRA); just wanted to check these two.

**Pull request merged**
