### PR TITLE
Fix kube-rbac-proxy image reference

### PR DESCRIPTION
**Pull request by jsafrane**
Use the one provided by CSO in the operator env. variables.
@openshift/storage

### CODE REVIEW

**Comment by yselkowitz** [comment]
Is this missing a reference in manifests/11_deployment.yaml perhaps?

**Comment by yselkowitz** [comment]
Tested this to see if it would fix the multi-arch breakage caused by #117, but it did not.  Trying an additional change (per my previous comment) now.

**Comment by yselkowitz** [comment]
I'm getting:
```
Failed to apply default image tag "${KUBE_RBAC_PROXY_IMAGE}": couldn't parse image reference "${KUBE_RBAC_PROXY_IMAGE}": invalid reference format: repository name must be lowercase
```

**Comment by gnufied** [comment]
@yselkowitz yeah I think it is missing a corresponding reference in `manifests/10_depoyment.yaml` and also `image-reference` in same directory.

**Comment by yselkowitz** [comment]
What confuses me is that there is no manifests/image-references at all here, which makes me wonder how this worked before?

**Comment by gnufied** [comment]
Oh - I was actually wrong. This repo does not need those image references and `manifests/xxx_deployment.yaml` , because those are referred in -- https://github.com/openshift/cluster-storage-operator/blob/master/manifests/10_deployment.yaml 

This operator is a second level operator and `manifest` directory of this repository is not directly managed by CVO and is there only for local deployment and testing.

**Comment by yselkowitz** [comment]
OK, things have been syncing slowly, so the cluster-storage-operator patch didn't land downstream until after #117 (and after the last full build).  Let me try patching that operator too and see if that helps.

**Comment by yselkowitz** [comment]
> Is this missing a reference in manifests/11_deployment.yaml (and README.md too) perhaps?

In the meantime, wouldn't these ^^^ additions still be needed for "local deployment and testing"?

**Comment by yselkowitz** [comment]
Thanks, this together with the CSO PR fixes the regression.  Do you want me to LGTM now or do you want to add the local workarounds in this PR?

**Comment by gnufied** [comment]
May be lgtm for now. I am not near computer.

On April 8, 2021, GitHub ***@***.***> wrote:
> Thanks, this together with the CSO PR fixes the regression. Do you
> want me to LGTM now or do you want to add the local workarounds in
> this PR?
>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/aws-ebs-csi-driver-
operator/pull/118#issuecomment-816305851>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAACFRYKBJWJFFD365LIY3THY6IVANCNFSM42TL7Q5A>.

**Pull request merged**
