### PR TITLE
[release-4.6] Bug 1915467: redeploy CSI Controller Deployment when secret change

### PR DESCRIPTION
**Pull request by bertinatto**
This is a  4.6 backport of PR https://github.com/openshift/aws-ebs-csi-driver-operator/pull/107

A drawback of this backport is that we had to bump library-go, which also caused the bump of k8s-related APIs.

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
Further discussion is needed to decide if this backport is too risky.

**Comment by bertinatto** [comment]
/hold cancel
We decided to go ahead with the backport, even though we're bumping library-go.

**Comment by bertinatto** [comment]
CC @openshift/storage

**Comment by jwforres** [comment]
(Patch Manager) given the size of this change due to the library.go bump and the fact that it is now using clients for a different version of kubernetes than runs on 4.6, I would like to see more details on the risks that were discussed

**Comment by bertinatto** [comment]
> (Patch Manager) given the size of this change due to the library.go bump and the fact that it is now using clients for a different version of kubernetes than runs on 4.6, I would like to see more details on the risks that were discussed

Regarding the k8s clients used in this PR (1.20), they are one version newer than the k8s version that runs on 4.6 (1.19). These version are compatible with each other, so we shouldn't have problems with that.

As for the library-go bump, the team considered the risk to be lower than the alternative solution, which was patching the `vendor/github.com/openshift/library-go/` directory with only the changes we needed to address this issue.

@jsafrane, would you like to add anything else?

**Comment by jsafrane** [comment]
We weighted bumping library-go and manually re-implementing the necessary functionality in `vendor/library-go` of the AWS operator, creating basically a fork of library-go there. We think that the new library-go, which is well tested, has lower risk than possibly introducing regressions in our much less tested library-go fork.

**Comment by jsafrane** [comment]
Now that I am looking at library-go, there *is* branch for 4.6, investigating if it can be used for cherry picks to 4.6.
/hold

**Comment by bertinatto** [comment]
Cherry-picked to `release-4.6` branch only the changes needed: https://github.com/openshift/library-go/pull/986.

Once that PR is merged, we can re-bump library-go in this PR.

**Comment by bertinatto** [comment]
1. https://github.com/openshift/library-go/pull/986 backported to library-go's `release-4.6` _as little as possible_ to make this PR work.
2. Then in df86e36116608159b2b6aeadfd24cbf180aef1ab I bumped library-go to `release4.6` (`go get github.com/openshift/library-go@release-4.6`).
3. Finally, I cherry-picked the fix for BZ 1915467 in e4b4b604c63c3b09d22e7ae5f97e89280b9536e1.

@jsafrane, do you agree to remove `hold`?

**Pull request merged**
