### PR TITLE
STOR-875: Implement custom keys in AWS EBS CSI driver operator

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-875
WIP until https://github.com/openshift/api/pull/1401 merges
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
Setting the driverConfig in the ClusterCSIDriver shows the change reflected in the default StorageClass:
```
$ oc get clustercsidriver ebs.csi.aws.com -o json | jq .spec
{
  "driverConfig": {
    "driverType": ""
  },
  "logLevel": "Normal",
  "managementState": "Managed",
  "observedConfig": null,
  "operatorLogLevel": "Normal",
  "unsupportedConfigOverrides": null
}
$ oc get sc gp3-csi -o json | jq .parameters
{
  "encrypted": "true",
  "type": "gp3"
}
$ oc edit clustercsidriver ebs.csi.aws.com
clustercsidriver.operator.openshift.io/ebs.csi.aws.com edited
$ oc get clustercsidriver ebs.csi.aws.com -o json | jq .spec
{
  "driverConfig": {
    "aws": {
      "kmsKeyARN": "arn:aws:kms:us-east-2:269733383066:alias/jdobson-kms01"
    },
    "driverType": "AWS"
  },
  "logLevel": "Normal",
  "managementState": "Managed",
  "observedConfig": null,
  "operatorLogLevel": "Normal",
  "unsupportedConfigOverrides": null
}
$ oc get sc gp3-csi -o json | jq .parameters
{
  "encrypted": "true",
  "kmsKeyId": "arn:aws:kms:us-east-2:269733383066:alias/jdobson-kms01",
  "type": "gp3"
}
```
Removing the config spec from the ClusterCSIDriver reverts the StorageClass:
```
$ oc edit clustercsidriver ebs.csi.aws.com
clustercsidriver.operator.openshift.io/ebs.csi.aws.com edited
$ oc get clustercsidriver ebs.csi.aws.com -o json | jq .spec
{
  "driverConfig": {
    "driverType": "AWS"
  },
  "logLevel": "Normal",
  "managementState": "Managed",
  "observedConfig": null,
  "operatorLogLevel": "Normal",
  "unsupportedConfigOverrides": null
}
$ oc get sc gp3-csi -o json | jq .parameters
{
  "encrypted": "true",
  "type": "gp3"
}
```

**Comment by Phaow** [comment]
Pre verfy with Install the aws cluster with the BYO 
```
---
apiVersion: v1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      rootVolume:
        kmsKeyARN: arn:aws:kms:us-east-2:************
  replicas: 3
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      rootVolume:
        kmsKeyARN: arn:aws:kms:us-east-2:************
  replicas: 3
metadata:
  name: pewang-0223a
platform:
  aws:
    region: us-east-2
pullSecret: HIDDEN
networking:
...
---
```
1. Edit the "ebs.csi.aws.com" clustercsidriver add the kmskey, all the preset storageclass add the kmskey parameter with the specified kmskeyArn
2. Create new storageClass without setting any kmskey and check it should without setting any keys as expected
3. Edit the "ebs.csi.aws.com" clustercsidriver update the kmskey, all the preset storageclass add the kmskey parameter with the new specified kmskeyArn
4. Edit the "ebs.csi.aws.com" clustercsidriver remove the kmskey, all the preset storageclass recoverd with no kmskey parameter
5. Hack our auto codes all using the key provision volume and launch regression test
The test results all looks good! Only 1 known bug https://issues.redhat.com/browse/OCPBUGS-5410 related snapshot, that the used kms key must add user permission for our ebs operation user (E.g. `pewang-0223a-x6q4n-aws-ebs-csi-driver-operator-x9sz2) .
`

**Comment by dobsonj** [comment]
> In addition, it seems `driverType: "AWS"` is a bit not serious. Could we set it as `AWS-EBS-CSI` maybe a bit better?

The [BYOK enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/installer/storage-class-encrypted.md#api-extensions) splits up the driver config spec based on platform. This `kmsKeyARN` field only applies to block volumes, but it's possible that we could add other fields to `AWSCSIDriverConfigSpec` in the future that modify the behavior of EFS for example. I think it's better to leave this as `driverType: "AWS"`

**Comment by Phaow** [comment]
@dobsonj Got it.  Make sense. Thanks for clarifying!

**Comment by Phaow** [comment]
Pre-verify with `4.13.0-0.ci.test-2023-03-02-022606-ci-ln-8zfgf5t-latest`(Pre-merged build) 
All the regression test passed: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/161522/console
```console
59 pass, 61 skip (27m12s)
```

**Pull request merged**
