### PR TITLE
STOR-947: support disabling default StorageClass via ClusterCSIDriver

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-947
Marking this WIP until openshift/library-go#1441 merges.
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/retitle STOR-947: support disabling default StorageClass via ClusterCSIDriver

**Comment by dobsonj** [comment]
> /docs-approved

/label docs-approved

**Comment by ropatil010** [comment]
/restest

Test Results: 
Verified on Standalone OCP cluster and Hypershift cluster. Same observation. 
Payload: 4.13.0-0.ci.test-2023-02-09-032006-ci-ln-j3sblj2-latest 
Hypershift operator: 4.13 
    - containerID: cri-o://5d465b864680e3f9ee0350a0b2c1c9d876e8bc4c9e5f4778fdb9863c8082cd08
      image: quay.io/hypershift/hypershift-operator:latest
      imageID: quay.io/hypershift/hypershift-operator@sha256:1c2f2a72ca13c354e642ba3e3dc4cadafca3e72ecaccdcea8769b7fd8ec6c53c

Mgmt cluster 
rohitpatil@ropatil-mac Downloads % oc get nodes
NAME                                         STATUS   ROLES                  AGE   VERSION
ip-10-0-131-211.us-east-2.compute.internal   Ready    worker                 39m   v1.26.0+85e5e7f
ip-10-0-140-158.us-east-2.compute.internal   Ready    control-plane,master   46m   v1.26.0+85e5e7f
ip-10-0-165-160.us-east-2.compute.internal   Ready    control-plane,master   47m   v1.26.0+85e5e7f
ip-10-0-185-20.us-east-2.compute.internal    Ready    worker                 37m   v1.26.0+85e5e7f
ip-10-0-205-229.us-east-2.compute.internal   Ready    control-plane,master   46m   v1.26.0+85e5e7f
ip-10-0-207-222.us-east-2.compute.internal   Ready    worker                 39m   v1.26.0+85e5e7f

Guest Cluster 
rohitpatil@ropatil-mac Downloads % oc get nodes
NAME                                         STATUS   ROLES    AGE   VERSION
ip-10-0-129-155.us-east-2.compute.internal   Ready    worker   16m   v1.26.0+85e5e7f
ip-10-0-138-156.us-east-2.compute.internal   Ready    worker   16m   v1.26.0+85e5e7f
ip-10-0-141-182.us-east-2.compute.internal   Ready    worker   16m   v1.26.0+85e5e7f
ip-10-0-142-220.us-east-2.compute.internal   Ready    worker   16m   v1.26.0+85e5e7f

Test Scenario Results: 
###################test0_Default started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState'

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   26m
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   26m

 change gp3-csi volumeBindingMode
 change gp3-csi reclaimPolicy
 change gp2-csi volumeBindingMode
 change gp2-csi reclaimPolicy

 Bydefault test change gp3-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/gp3-csi patched
 Bydefault result oc get sc gp3-csi
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   27m

 Bydefault test change gp2-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/gp2-csi patched
 Bydefault result oc get sc gp2-csi
NAME      PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   27m

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   27m
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   27m

oc delete sc
storageclass.storage.k8s.io "gp2-csi" deleted
storageclass.storage.k8s.io "gp3-csi" deleted

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   4s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   2s
###################test1_Removed started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState' 
  storageClassState: Removed

 Removed test change gp3-csi allowVolumeExpansion to false
 Removed test change gp2-csi allowVolumeExpansion to false

 Removed result oc get sc
No resources found
###################test2_Managed started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   15s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   15s

 change gp3-csi volumeBindingMode
 change gp3-csi reclaimPolicy
 change gp2-csi volumeBindingMode
 change gp2-csi reclaimPolicy

 Managed test change gp3-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/gp3-csi patched
 Managed result oc get sc gp3-csi
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   25s

 Bydefault test change gp2-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/gp2-csi patched
 Bydefault result oc get sc gp2-csi
NAME      PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   28s

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   29s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   29s

oc delete sc
storageclass.storage.k8s.io "gp2-csi" deleted
storageclass.storage.k8s.io "gp3-csi" deleted

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   3s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   1s
###################test3_Unmanaged started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   61s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   59s

 change gp3-csi volumeBindingMode
 change gp3-csi reclaimPolicy
 change gp2-csi volumeBindingMode
 change gp2-csi reclaimPolicy

 Unmanaged test change gp3-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/gp3-csi patched
 Unmanaged result oc get sc gp3-csi
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   false                  70s

 Unmanaged test change gp2-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/gp2-csi patched
 Unmanaged result oc get sc gp2-csi
NAME      PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi   ebs.csi.aws.com   Delete          WaitForFirstConsumer   false                  74s

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   false                  76s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   false                  74s

oc delete sc
storageclass.storage.k8s.io "gp2-csi" deleted
storageclass.storage.k8s.io "gp3-csi" deleted

oc get sc
No resources found###################test4a_Multiple Managed default sc started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   29s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   29s
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   33s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   33s
testsc (default)    ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   2s
###################test4b_Removed started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc and check gp3-csi,gp2-csi should not be there and testsc should be there
NAME               PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
testsc (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   45s
###################test4c_Managed sc started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc all should be present now gp2-csi, gp3-csi, testsc
NAME               PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi            ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   21s
gp3-csi            ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   21s
testsc (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   86s
Deleting all sc
storageclass.storage.k8s.io "testsc" deleted
storageclass.storage.k8s.io "gp2-csi" deleted
storageclass.storage.k8s.io "gp3-csi" deleted

oc get sc gp2-csi and gp3-csi should be back to default
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   3s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   2s
###################test5a_Managed default sc started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   43s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   42s
###################test5b_Unmanaged default sc started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   2m2s
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   2m1s
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched
Applying patch to sc gp3-csi for changing to non default
storageclass.storage.k8s.io/gp3-csi patched

oc get sc
NAME               PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi            ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   2m8s
gp3-csi            ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   2m7s
testsc (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   5s
###################test5c_Removed sc started #################
oc get clustercsidriver ebs.csi.aws.com -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc gp3-csi,gp2-csi should not be there, testsc should be there
NAME               PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
testsc (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   35s
Deleting sc testsc
storageclass.storage.k8s.io "testsc" deleted
Deleting sc gp2-csi
Deleting sc gp3-csi

oc get sc
No resources found
########################t###################t###################t

/label qe-approved

**Pull request merged**
